#!/usr/bin/env bash
# .claude/log-event.sh — session resilience logger
#
# Invoked by Claude Code hooks. Receives the hook JSON payload on stdin.
# Appends one line to .claude/session-log.md and rewrites .claude/resume-state.md
# so the next session can pick up after a crash or API outage.
#
# Design rules:
#   - Never fails (exits 0 unconditionally).
#   - No network. Uses only coreutils, jq, git, flock.
#   - Concurrent-safe via flock.
#   - Locates the repo via its own script path, so it works regardless of CWD.

set +e
umask 022

EVENT="${1:-unknown}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOG_DIR="${REPO_ROOT}/.claude"
LOG_FILE="${LOG_DIR}/session-log.md"
STATE_FILE="${LOG_DIR}/resume-state.md"
ERR_FILE="${LOG_DIR}/hook-errors.log"
LOCK_FILE="${LOG_DIR}/.log.lock"

mkdir -p "${LOG_DIR}" 2>/dev/null
touch "${LOG_FILE}" "${STATE_FILE}" "${ERR_FILE}" 2>/dev/null

# Redirect stray stderr to the error log — a logging hiccup must not
# surface to the user or block a tool call.
exec 2>>"${ERR_FILE}"

TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BRANCH="$(git -C "${REPO_ROOT}" branch --show-current 2>/dev/null)"
[[ -z "${BRANCH}" ]] && BRANCH="(detached)"

# Slurp stdin — some events have no payload, that is fine.
PAYLOAD="$(cat 2>/dev/null || true)"

json_get() {
  # usage: json_get <jq-expression>
  # Returns empty on missing field, malformed JSON, or empty input.
  local expr="$1"
  [[ -z "${PAYLOAD}" ]] && return
  printf '%s' "${PAYLOAD}" | jq -r "try (${expr}) // empty" 2>/dev/null \
    | tr '\n\r\t' '   '
}

truncate_str() {
  # usage: truncate_str <max-chars>
  local max="${1:-120}"
  cut -c1-"${max}"
}

SUMMARY=""
case "${EVENT}" in
  session-start)
    SOURCE="$(json_get '.source' | truncate_str 40)"
    SUMMARY="source=${SOURCE:-unknown}"
    ;;
  user-prompt)
    PROMPT="$(json_get '.prompt' | truncate_str 160)"
    SUMMARY="prompt=\"${PROMPT}\""
    ;;
  tool-use)
    TOOL="$(json_get '.tool_name' | truncate_str 40)"
    TARGET="$(json_get '.tool_input.file_path // .tool_input.command // .tool_input.path // .tool_input.pattern' | truncate_str 160)"
    SUMMARY="tool=${TOOL} target=\"${TARGET}\""
    ;;
  stop)
    SUMMARY="session-stop"
    ;;
  *)
    SUMMARY="(${EVENT})"
    ;;
esac

# --- Emit SessionStart additionalContext BEFORE rewriting state. -----------
# We want the new session to see the PREVIOUS session's state, not its own
# still-forming one.
if [[ "${EVENT}" == "session-start" ]] && [[ -s "${STATE_FILE}" ]]; then
  PRIOR_STATE="$(cat "${STATE_FILE}" 2>/dev/null)"
  if [[ -n "${PRIOR_STATE}" ]]; then
    jq -n \
      --arg c "${PRIOR_STATE}" \
      '{hookSpecificOutput:{hookEventName:"SessionStart", additionalContext:$c}}' \
      2>/dev/null || true
  fi
fi

# --- Append to session-log.md under flock. --------------------------------
{
  flock -w 5 9 || exit 0
  if [[ ! -s "${LOG_FILE}" ]]; then
    cat >"${LOG_FILE}" <<'HDR'
# Session Log

Append-only audit trail written by `.claude/log-event.sh`.
One line per hook event. Newest entries at the bottom.

Format: `` `<iso-ts>` **<event>** branch=`<branch>` <summary> ``

See `.claude/README.md` for the full schema and how to read this file.

HDR
  fi
  printf -- '- `%s` **%s** branch=`%s` %s\n' \
    "${TS}" "${EVENT}" "${BRANCH}" "${SUMMARY}" >>"${LOG_FILE}"
} 9>"${LOCK_FILE}"

# --- Rewrite resume-state.md. Single-writer snapshot. ---------------------
GIT_STATUS="$(git -C "${REPO_ROOT}" status --short 2>/dev/null)"
GIT_AHEAD="$(git -C "${REPO_ROOT}" rev-list --left-right --count \
  "origin/${BRANCH}...${BRANCH}" 2>/dev/null)"
[[ -z "${GIT_AHEAD}" ]] && GIT_AHEAD="? ?"

LAST_PROMPT_LINE="$(grep -- '\*\*user-prompt\*\*' "${LOG_FILE}" 2>/dev/null | tail -1)"
LAST_TOOLS="$(grep -- '\*\*tool-use\*\*' "${LOG_FILE}" 2>/dev/null | tail -5)"

TMP_STATE="$(mktemp "${LOG_DIR}/.state.XXXXXX" 2>/dev/null)" || TMP_STATE="${STATE_FILE}.tmp"
cat >"${TMP_STATE}" <<EOF
# Resume State

_Auto-generated by \`.claude/log-event.sh\`. Hand-edit only if you know why —
the next hook invocation will overwrite this file._

- **Snapshot at:** \`${TS}\`
- **Branch:** \`${BRANCH}\`
- **origin/${BRANCH} vs local (behind ahead):** \`${GIT_AHEAD}\`
- **Last event:** \`${EVENT}\` — ${SUMMARY}

## Git status (\`--short\`)

\`\`\`
${GIT_STATUS:-(clean)}
\`\`\`

## Last user prompt

${LAST_PROMPT_LINE:-_none recorded yet_}

## Last 5 tool uses

${LAST_TOOLS:-_none recorded yet_}

---
To resume after a crash:
1. Read this file for the last known state.
2. Read \`.claude/session-log.md\` for the full event trail.
3. Read \`_notes.md\` for the curated active-task list.
EOF
mv -f "${TMP_STATE}" "${STATE_FILE}" 2>/dev/null || true

exit 0
